## Importing Libraries

In [5]:
import pandas as pd
import numpy as np

## Loading into Dataframe

In [6]:
demo = pd.read_csv(r'D:\Study\Machine Learning Projects\Adversal Event Signal Ranker\Data\Dataset\Data Files\DEMO25Q4.txt',sep = '$' , encoding='latin1')

C:\Users\Rajvardhan\AppData\Local\Temp\ipykernel_19484\3964152296.py:1: DtypeWarning: Columns (0: to_mfr) have mixed types. Specify dtype option on import or set low_memory=False.
  demo = pd.read_csv(r'D:\Study\Machine Learning Projects\Adversal Event Signal Ranker\Data\Dataset\Data Files\DEMO25Q4.txt',sep = '$' , encoding='latin1')

In [7]:
demo.head()

,primaryid,caseid,caseversion,i_f_code,event_dt,mfr_dt,init_fda_dt,fda_dt,rept_cod,auth_num,...,age_grp,sex,e_sub,wt,wt_cod,rept_dt,to_mfr,occp_cod,reporter_country,occr_country
0,100324053,10032405,3,F,NaN,20251110,20140320,20251120,EXP,NaN,...,NaN,F,Y,NaN,NaN,20251120,NaN,NaN,CA,NaN
1,1012809821,10128098,21,F,20140219.0,20251003,20140428,20251010,EXP,NaN,...,A,F,Y,70.00,KG,20251010,NaN,MD,CA,CA
2,101406268,10140626,8,F,20120301.0,20250929,20140429,20251007,EXP,NaN,...,A,F,Y,77.09,KG,20251007,NaN,CN,US,US
3,101515934,10151593,4,F,NaN,20251014,20140505,20251020,EXP,NaN,...,A,F,Y,NaN,NaN,20251020,NaN,HP,EU,EU
4,1016133068,10161330,68,F,NaN,20251002,20140509,20251009,EXP,NaN,...,E,F,Y,63.00,KG,20251009,NaN,CN,CA,CA

In [8]:
demo.shape

(385288, 25)

In [9]:
demo = demo[['primaryid' , 'event_dt' , 'occr_country']]

In [10]:
demo

         primaryid    event_dt occr_country
0        100324053         NaN          NaN
1       1012809821  20140219.0           CA
2        101406268  20120301.0           US
3        101515934         NaN           EU
4       1016133068         NaN           CA
...            ...         ...          ...
385283   984835519  20140101.0           CA
385284   986902626  20131009.0           CA
385285    98821072         NaN           EU
385286    99947975         NaN           EU
385287    99948243         NaN           US

[385288 rows x 3 columns]

In [11]:
drug = pd.read_csv(r'D:\Study\Machine Learning Projects\Adversal Event Signal Ranker\Data\Dataset\Data Files\DRUG25Q4.txt',sep='$' , encoding='latin1')

In [12]:
drug.shape

(1815349, 20)

In [13]:
drug.head()

,primaryid,caseid,drug_seq,role_cod,drugname,prod_ai,val_vbm,route,dose_vbm,cum_dose_chr,cum_dose_unit,dechal,rechal,lot_num,exp_dt,nda_num,dose_amt,dose_unit,dose_form,dose_freq
0,100324053,10032405,1,PS,CEFPROZIL,CEFPROZIL,1,Unknown,"UNK UNK,Two Times a Day,",NaN,NaN,D,NaN,NaN,NaN,65381.0,NaN,NaN,NaN,QD
1,100324053,10032405,2,SS,PNEUMOCOCCAL VACCINE POLYVALENT NOS,"PNEUMOCOCCAL VACCINE, POLYVALENT",1,Unknown,"UNK, once",NaN,NaN,D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,100324053,10032405,3,SS,PNEUMOCOCCAL 13-VALENT CONJUGATE VACCINE,PNEUMOCOCCAL 13-VALENT CONJUGATE VACCINE,1,Unknown,"1 DF,UNK,",NaN,NaN,D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,100324053,10032405,4,SS,PNEUMOCOCCAL 7-VALENT CONJUGATE VACCINE (DIPHT...,PNEUMOCOCCAL 7-VALENT CONJUGATE VACCINE (DIPHT...,1,Unknown,"1 DF,UNK,",NaN,NaN,D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,100324053,10032405,5,SS,PNEUMOVAX 23,"PNEUMOCOCCAL VACCINE, POLYVALENT 23",1,Unknown,UNK,NaN,NaN,D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
drug['role_cod'].value_counts()

role_cod
SS    687320
C     679402
PS    437206
I      11340
DN        81
Name: count, dtype: int64

In [15]:
drug = drug[drug['role_cod'] == 'PS']

In [16]:
drug = drug[['primaryid' , 'drugname']]

In [17]:
drug.head()

     primaryid        drugname
0    100324053       CEFPROZIL
6   1012809821          XOLAIR
30   101406268          MIRENA
31   101515934  VALGANCICLOVIR
37  1016133068         ACTEMRA

In [18]:
drug.shape

(437206, 2)

In [19]:
# D:\Study\Machine Learning Projects\Adversal Event Signal Ranker\Data\faers_ascii_2025Q4\ASCII\OUTC25Q4.txt
outcome = pd.read_csv(r'Data\Dataset\Data Files\OUTC25Q4.txt',sep='$' , encoding = 'latin1')

In [20]:
outcome.head()

    primaryid    caseid outc_cod
0   100324053  10032405       DE
1   100324053  10032405       OT
2  1012809821  10128098       OT
3   101406268  10140626       HO
4   101406268  10140626       OT

In [21]:
outcome.shape

(289721, 3)

In [22]:
outcome = outcome[['primaryid' , 'outc_cod']]

In [23]:
outcome.head()

    primaryid outc_cod
0   100324053       DE
1   100324053       OT
2  1012809821       OT
3   101406268       HO
4   101406268       OT

In [24]:
reaction = pd.read_csv(r'D:\Study\Machine Learning Projects\Adversal Event Signal Ranker\Data\Dataset\Data Files\REAC25Q4.txt',sep = '$' , encoding = 'latin1')

In [25]:
reaction.shape

(1349105, 4)

In [26]:
reaction.head()

    primaryid    caseid                                     pt drug_rec_act
0   100324053  10032405                       Drug ineffective          NaN
1   100324053  10032405                        Drug resistance          NaN
2   100324053  10032405                Meningitis pneumococcal          NaN
3  1012809821  10128098                Injection site reaction          NaN
4  1012809821  10128098  General physical health deterioration          NaN

In [27]:
reaction = reaction[['primaryid' , 'pt']]

In [28]:
reaction.shape

(1349105, 2)

In [29]:
drug

          primaryid               drugname
0         100324053              CEFPROZIL
6        1012809821                 XOLAIR
30        101406268                 MIRENA
31        101515934         VALGANCICLOVIR
37       1016133068                ACTEMRA
...             ...                    ...
1815281   984835519  SANDOSTATIN LAR DEPOT
1815286   986902626                ACTEMRA
1815323    98821072           CYCLOSPORINE
1815330    99947975           CYCLOSPORINE
1815345    99948243             LISINOPRIL

[437206 rows x 2 columns]

In [30]:
reaction

          primaryid                                     pt
0         100324053                       Drug ineffective
1         100324053                        Drug resistance
2         100324053                Meningitis pneumococcal
3        1012809821                Injection site reaction
4        1012809821  General physical health deterioration
...             ...                                    ...
1349100    99948243                  Intestinal angioedema
1349101    99948243                              Diarrhoea
1349102    99948243                               Vomiting
1349103    99948243                                  Cough
1349104    99948243                         Abdominal pain

[1349105 rows x 2 columns]

In [31]:
outcome

         primaryid outc_cod
0        100324053       DE
1        100324053       OT
2       1012809821       OT
3        101406268       HO
4        101406268       OT
...            ...      ...
289716   986902626       OT
289717    98821072       OT
289718    99947975       OT
289719    99948243       HO
289720    99948243       OT

[289721 rows x 2 columns]

In [32]:
demo

         primaryid    event_dt occr_country
0        100324053         NaN          NaN
1       1012809821  20140219.0           CA
2        101406268  20120301.0           US
3        101515934         NaN           EU
4       1016133068         NaN           CA
...            ...         ...          ...
385283   984835519  20140101.0           CA
385284   986902626  20131009.0           CA
385285    98821072         NaN           EU
385286    99947975         NaN           EU
385287    99948243         NaN           US

[385288 rows x 3 columns]

## Merging the datasets

In [33]:
df = drug.merge(reaction , how='inner' , on='primaryid')

In [34]:
df.shape

(1898464, 3)

In [35]:
df = df.merge(outcome , how='left' , on = 'primaryid')

In [36]:
df.shape

(3029286, 4)

In [37]:
df = df.merge(demo , how='left' , on = 'primaryid')

In [38]:
df.shape

(3029286, 6)

In [39]:
df.head()

,primaryid,drugname,pt,outc_cod,event_dt,occr_country
0,100324053,CEFPROZIL,Drug ineffective,DE,NaN,NaN
1,100324053,CEFPROZIL,Drug ineffective,OT,NaN,NaN
2,100324053,CEFPROZIL,Drug resistance,DE,NaN,NaN
3,100324053,CEFPROZIL,Drug resistance,OT,NaN,NaN
4,100324053,CEFPROZIL,Meningitis pneumococcal,DE,NaN,NaN

In [40]:
df.rename(columns={'pt' : 'reaction' , 'outc_cod' : 'outcome_code' , 'event_dt' : 'date' , 'occr_country' : 'country'},inplace=True)

In [41]:
df

,primaryid,drugname,reaction,outcome_code,date,country
0,100324053,CEFPROZIL,Drug ineffective,DE,NaN,NaN
1,100324053,CEFPROZIL,Drug ineffective,OT,NaN,NaN
2,100324053,CEFPROZIL,Drug resistance,DE,NaN,NaN
3,100324053,CEFPROZIL,Drug resistance,OT,NaN,NaN
4,100324053,CEFPROZIL,Meningitis pneumococcal,DE,NaN,NaN
...,...,...,...,...,...,...
3029281,99948243,LISINOPRIL,Vomiting,OT,NaN,US
3029282,99948243,LISINOPRIL,Cough,HO,NaN,US
3029283,99948243,LISINOPRIL,Cough,OT,NaN,US
3029284,99948243,LISINOPRIL,Abdominal pain,HO,NaN,US
3029285,99948243,LISINOPRIL,Abdominal pain,OT,NaN,US

## Informatrion About dataset

In [42]:
df.head()

   primaryid   drugname                 reaction outcome_code  date country
0  100324053  CEFPROZIL         Drug ineffective           DE   NaN     NaN
1  100324053  CEFPROZIL         Drug ineffective           OT   NaN     NaN
2  100324053  CEFPROZIL          Drug resistance           DE   NaN     NaN
3  100324053  CEFPROZIL          Drug resistance           OT   NaN     NaN
4  100324053  CEFPROZIL  Meningitis pneumococcal           DE   NaN     NaN

In [43]:
df.tail()

         primaryid    drugname        reaction outcome_code  date country
3029281   99948243  LISINOPRIL        Vomiting           OT   NaN      US
3029282   99948243  LISINOPRIL           Cough           HO   NaN      US
3029283   99948243  LISINOPRIL           Cough           OT   NaN      US
3029284   99948243  LISINOPRIL  Abdominal pain           HO   NaN      US
3029285   99948243  LISINOPRIL  Abdominal pain           OT   NaN      US

In [44]:
df.sample(10)

,primaryid,drugname,reaction,outcome_code,date,country
1581441,257327303,SIMPONI,Plantar fasciitis,OT,20240101.0,CA
1011810,245874508,FENFLURAMINE HYDROCHLORIDE,Prescribed underdose,DE,NaN,JP
1345065,254248567,LEVOTHYROXINE SODIUM,Cognitive disorder,OT,20180207.0,GB
2923070,262000561,REZLIDHIA,Insomnia,NaN,20250101.0,US
86869,1692759815,TEDUGLUTIDE,Product packaging quantity issue,OT,20190101.0,US
407235,2068971927,IDURSULFASE,Tachycardia,DE,20210630.0,EU
869421,238500742,VEDOLIZUMAB,Lower respiratory tract infection,OT,NaN,ZA
139553,1791303624,HUMAN IMMUNOGLOBULIN G,Salivary gland enlargement,OT,20220425.0,US
2877698,261894381,MOMELOTINIB DIHYDROCHLORIDE,Epilepsy,OT,20251201.0,AE
67206,1608138320,ALENDRONIC ACID,Pyrexia,OT,NaN,CA

In [45]:
df.shape

(3029286, 6)

In [46]:
df.dtypes

primaryid         int64
drugname            str
reaction            str
outcome_code        str
date            float64
country             str
dtype: object

In [47]:
df.columns

Index(['primaryid', 'drugname', 'reaction', 'outcome_code', 'date', 'country'], dtype='str')

In [48]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3029286 entries, 0 to 3029285
Data columns (total 6 columns):
 #   Column        Dtype
---  ------        -----
 0   primaryid     int64
 1   drugname      str
 2   reaction      str
 3   outcome_code  str
 4   date          float64
 5   country       str
dtypes: float64(1), int64(1), str(4)
memory usage: 231.4 MB

In [49]:
df.describe()

          primaryid          date
count  3.029286e+06  1.550508e+06
mean   6.560605e+08  2.022649e+07
std    8.034425e+08  3.401151e+04
min    4.202112e+07  1.920090e+07
25%    2.551509e+08  2.021053e+07
50%    2.599747e+08  2.024020e+07
75%    2.620275e+08  2.025040e+07
max    2.168458e+10  2.026112e+07

In [50]:
df.isnull().sum()

primaryid             0
drugname              0
reaction              0
outcome_code     426878
date            1478778
country          242013
dtype: int64

## Data cleaning steps

### Handling Duplicates

In [51]:
df.duplicated(subset=['primaryid','drugname', 'reaction']).sum()

np.int64(1696521)

In [52]:
df.drop_duplicates(subset=['primaryid','drugname', 'reaction'] , inplace = True)

In [53]:
df.shape

(1332765, 6)

In [54]:
df.head()

,primaryid,drugname,reaction,outcome_code,date,country
0,100324053,CEFPROZIL,Drug ineffective,DE,NaN,NaN
2,100324053,CEFPROZIL,Drug resistance,DE,NaN,NaN
4,100324053,CEFPROZIL,Meningitis pneumococcal,DE,NaN,NaN
6,1012809821,XOLAIR,Injection site reaction,OT,20140219.0,CA
7,1012809821,XOLAIR,General physical health deterioration,OT,20140219.0,CA

In [55]:
df.isnull().sum()

primaryid            0
drugname             0
reaction             0
outcome_code    386811
date            642791
country          86419
dtype: int64

In [56]:
df

,primaryid,drugname,reaction,outcome_code,date,country
0,100324053,CEFPROZIL,Drug ineffective,DE,NaN,NaN
2,100324053,CEFPROZIL,Drug resistance,DE,NaN,NaN
4,100324053,CEFPROZIL,Meningitis pneumococcal,DE,NaN,NaN
6,1012809821,XOLAIR,Injection site reaction,OT,20140219.0,CA
7,1012809821,XOLAIR,General physical health deterioration,OT,20140219.0,CA
...,...,...,...,...,...,...
3029276,99948243,LISINOPRIL,Intestinal angioedema,HO,NaN,US
3029278,99948243,LISINOPRIL,Diarrhoea,HO,NaN,US
3029280,99948243,LISINOPRIL,Vomiting,HO,NaN,US
3029282,99948243,LISINOPRIL,Cough,HO,NaN,US
3029284,99948243,LISINOPRIL,Abdominal pain,HO,NaN,US

In [57]:
df['drugname'] =  df['drugname'].str.lower()
df['reaction'] = df['reaction'].str.lower()

In [58]:
df

,primaryid,drugname,reaction,outcome_code,date,country
0,100324053,cefprozil,drug ineffective,DE,NaN,NaN
2,100324053,cefprozil,drug resistance,DE,NaN,NaN
4,100324053,cefprozil,meningitis pneumococcal,DE,NaN,NaN
6,1012809821,xolair,injection site reaction,OT,20140219.0,CA
7,1012809821,xolair,general physical health deterioration,OT,20140219.0,CA
...,...,...,...,...,...,...
3029276,99948243,lisinopril,intestinal angioedema,HO,NaN,US
3029278,99948243,lisinopril,diarrhoea,HO,NaN,US
3029280,99948243,lisinopril,vomiting,HO,NaN,US
3029282,99948243,lisinopril,cough,HO,NaN,US
3029284,99948243,lisinopril,abdominal pain,HO,NaN,US

### Handling missing values and outcome_code columns

In [59]:
df['outcome_code'] = df['outcome_code'].fillna('UN')

In [60]:
df['outcome_code'] = df['outcome_code'].str.strip()

In [61]:
df.isnull().sum()

primaryid            0
drugname             0
reaction             0
outcome_code         0
date            642791
country          86419
dtype: int64

In [62]:
df['outcome_code'].value_counts()

outcome_code
OT    511382
UN    386811
HO    289077
DE     69725
DS     31595
LT     28087
CA     14240
RI      1848
Name: count, dtype: int64

In [63]:
dictionary = {
    'DE' : 10,
    'LT' : 8,
    'HO' : 7,
    'DS' : 6,
    'CA' : 5,
    'RI' : 4,
    'OT' : 2,
    'UN' : 2
}

In [64]:
df['severity_score'] = df['outcome_code'].map(dictionary)

In [65]:
df

,primaryid,drugname,reaction,outcome_code,date,country,severity_score
0,100324053,cefprozil,drug ineffective,DE,NaN,NaN,10
2,100324053,cefprozil,drug resistance,DE,NaN,NaN,10
4,100324053,cefprozil,meningitis pneumococcal,DE,NaN,NaN,10
6,1012809821,xolair,injection site reaction,OT,20140219.0,CA,2
7,1012809821,xolair,general physical health deterioration,OT,20140219.0,CA,2
...,...,...,...,...,...,...,...
3029276,99948243,lisinopril,intestinal angioedema,HO,NaN,US,7
3029278,99948243,lisinopril,diarrhoea,HO,NaN,US,7
3029280,99948243,lisinopril,vomiting,HO,NaN,US,7
3029282,99948243,lisinopril,cough,HO,NaN,US,7
3029284,99948243,lisinopril,abdominal pain,HO,NaN,US,7

In [66]:
df['outcome_code'].value_counts()

outcome_code
OT    511382
UN    386811
HO    289077
DE     69725
DS     31595
LT     28087
CA     14240
RI      1848
Name: count, dtype: int64

In [67]:
df['severity_score'].value_counts()

severity_score
2     898193
7     289077
10     69725
6      31595
8      28087
5      14240
4       1848
Name: count, dtype: int64

In [68]:
df

,primaryid,drugname,reaction,outcome_code,date,country,severity_score
0,100324053,cefprozil,drug ineffective,DE,NaN,NaN,10
2,100324053,cefprozil,drug resistance,DE,NaN,NaN,10
4,100324053,cefprozil,meningitis pneumococcal,DE,NaN,NaN,10
6,1012809821,xolair,injection site reaction,OT,20140219.0,CA,2
7,1012809821,xolair,general physical health deterioration,OT,20140219.0,CA,2
...,...,...,...,...,...,...,...
3029276,99948243,lisinopril,intestinal angioedema,HO,NaN,US,7
3029278,99948243,lisinopril,diarrhoea,HO,NaN,US,7
3029280,99948243,lisinopril,vomiting,HO,NaN,US,7
3029282,99948243,lisinopril,cough,HO,NaN,US,7
3029284,99948243,lisinopril,abdominal pain,HO,NaN,US,7

In [69]:
df['country'] = df['country'].fillna('NN')

In [70]:
df.isnull().sum()

primaryid              0
drugname               0
reaction               0
outcome_code           0
date              642791
country                0
severity_score         0
dtype: int64

### Handling date columns

In [71]:
df['report_date'] = pd.to_datetime(df['date'], errors='coerce')

In [72]:
df

,primaryid,drugname,reaction,outcome_code,date,country,severity_score,report_date
0,100324053,cefprozil,drug ineffective,DE,NaN,NN,10,NaT
2,100324053,cefprozil,drug resistance,DE,NaN,NN,10,NaT
4,100324053,cefprozil,meningitis pneumococcal,DE,NaN,NN,10,NaT
6,1012809821,xolair,injection site reaction,OT,20140219.0,CA,2,1970-01-01 00:00:00.020140219
7,1012809821,xolair,general physical health deterioration,OT,20140219.0,CA,2,1970-01-01 00:00:00.020140219
...,...,...,...,...,...,...,...,...
3029276,99948243,lisinopril,intestinal angioedema,HO,NaN,US,7,NaT
3029278,99948243,lisinopril,diarrhoea,HO,NaN,US,7,NaT
3029280,99948243,lisinopril,vomiting,HO,NaN,US,7,NaT
3029282,99948243,lisinopril,cough,HO,NaN,US,7,NaT
3029284,99948243,lisinopril,abdominal pain,HO,NaN,US,7,NaT

In [73]:
df.drop(columns={'date' , 'report_date'},inplace=True)

In [74]:
df.isnull().sum()

primaryid         0
drugname          0
reaction          0
outcome_code      0
country           0
severity_score    0
dtype: int64

In [75]:
df

,primaryid,drugname,reaction,outcome_code,country,severity_score
0,100324053,cefprozil,drug ineffective,DE,NN,10
2,100324053,cefprozil,drug resistance,DE,NN,10
4,100324053,cefprozil,meningitis pneumococcal,DE,NN,10
6,1012809821,xolair,injection site reaction,OT,CA,2
7,1012809821,xolair,general physical health deterioration,OT,CA,2
...,...,...,...,...,...,...
3029276,99948243,lisinopril,intestinal angioedema,HO,US,7
3029278,99948243,lisinopril,diarrhoea,HO,US,7
3029280,99948243,lisinopril,vomiting,HO,US,7
3029282,99948243,lisinopril,cough,HO,US,7
3029284,99948243,lisinopril,abdominal pain,HO,US,7

## Pushing data to MySql

In [76]:
from sqlalchemy import create_engine

In [77]:
conn = create_engine("mysql+pymysql://root:1771@localhost/pharma_safety")

In [79]:
df

,primaryid,drugname,reaction,outcome_code,country,severity_score
0,100324053,cefprozil,drug ineffective,DE,NN,10
2,100324053,cefprozil,drug resistance,DE,NN,10
4,100324053,cefprozil,meningitis pneumococcal,DE,NN,10
6,1012809821,xolair,injection site reaction,OT,CA,2
7,1012809821,xolair,general physical health deterioration,OT,CA,2
...,...,...,...,...,...,...
3029276,99948243,lisinopril,intestinal angioedema,HO,US,7
3029278,99948243,lisinopril,diarrhoea,HO,US,7
3029280,99948243,lisinopril,vomiting,HO,US,7
3029282,99948243,lisinopril,cough,HO,US,7
3029284,99948243,lisinopril,abdominal pain,HO,US,7

In [80]:
df.to_sql(
    name='faers_raw',
    con=conn,
    if_exists='replace',
    index=False,
    chunksize=1000
)

1332765

In [81]:
df.to_csv('Fares Raw.csv')