## Importing Libraries

In [3]:
from sqlalchemy import create_engine
import pandas as pd
import numpy as np

## Connecting To database

In [4]:
conn = create_engine('mysql+pymysql://root:1771@localhost/pharma_safety')
print("Connected Succesfully !!!")

Connected Succesfully !!!

In [5]:
df = pd.read_sql("""
SELECT * FROM faers_raw ;
""" , conn)

In [6]:
df

,primaryid,drugname,reaction,outcome_code,country,severity_score
0,100324053,cefprozil,drug ineffective,DE,NN,10
1,100324053,cefprozil,drug resistance,DE,NN,10
2,100324053,cefprozil,meningitis pneumococcal,DE,NN,10
3,1012809821,xolair,injection site reaction,OT,CA,2
4,1012809821,xolair,general physical health deterioration,OT,CA,2
...,...,...,...,...,...,...
1332760,99948243,lisinopril,intestinal angioedema,HO,US,7
1332761,99948243,lisinopril,diarrhoea,HO,US,7
1332762,99948243,lisinopril,vomiting,HO,US,7
1332763,99948243,lisinopril,cough,HO,US,7
1332764,99948243,lisinopril,abdominal pain,HO,US,7

## Calculating complaint count , maximum sevirity score and avgerage severity score

In [108]:
demo_df = df.groupby(['drugname' , 'reaction'])['primaryid'].count().reset_index(name = 'complaint_count')

In [109]:
demo_df

,drugname,reaction,complaint_count
0,.alpha.1-proteinase inhibitor human,abdominal abscess,1
1,.alpha.1-proteinase inhibitor human,abdominal discomfort,2
2,.alpha.1-proteinase inhibitor human,abdominal distension,1
3,.alpha.1-proteinase inhibitor human,abdominal hernia,1
4,.alpha.1-proteinase inhibitor human,abdominal pain,4
...,...,...,...
388368,zyvox,skin disorder,1
388369,zyvox,skin swelling,1
388370,zyvox,thrombocytopenia,3
388371,zyvox,vomiting,1
388372,zyvox,white blood cell count decreased,1

In [9]:
demo_df['max_severity_score'] = df.groupby(['drugname' , 'reaction'])['severity_score'].max().reset_index(name = 'max_severity_score')['max_severity_score']

In [10]:
demo_df['avg_severity_score'] = df.groupby(['drugname' , 'reaction'])['severity_score'].mean().reset_index(name = 'avg_severity_score')['avg_severity_score']

In [11]:
demo_df

,drugname,reaction,complaint_count,max_severity_score,avg_severity_score
0,.alpha.1-proteinase inhibitor human,abdominal abscess,1,7,7.000000
1,.alpha.1-proteinase inhibitor human,abdominal discomfort,2,7,4.500000
2,.alpha.1-proteinase inhibitor human,abdominal distension,1,7,7.000000
3,.alpha.1-proteinase inhibitor human,abdominal hernia,1,7,7.000000
4,.alpha.1-proteinase inhibitor human,abdominal pain,4,7,4.500000
...,...,...,...,...,...
388368,zyvox,skin disorder,1,4,4.000000
388369,zyvox,skin swelling,1,2,2.000000
388370,zyvox,thrombocytopenia,3,8,7.333333
388371,zyvox,vomiting,1,4,4.000000
388372,zyvox,white blood cell count decreased,1,7,7.000000

In [12]:
demo_df.isnull().sum()

drugname              0
reaction              0
complaint_count       0
max_severity_score    0
avg_severity_score    0
dtype: int64

In [ ]:
demo_df['drugname'] == ''

## Caculating Complaints count , maximum severity score and average severity severity score by second way

In [13]:
# Step 1: groupby on the FULL df — no filtering before this
pairs = df.groupby(['drugname', 'reaction']).agg(
    complaint_count    = ('primaryid', 'count'),
    max_severity_score = ('severity_score', 'max'),
    avg_severity_score = ('severity_score', 'mean')
).reset_index()

In [14]:
pairs

,drugname,reaction,complaint_count,max_severity_score,avg_severity_score
0,.alpha.1-proteinase inhibitor human,abdominal abscess,1,7,7.000000
1,.alpha.1-proteinase inhibitor human,abdominal discomfort,2,7,4.500000
2,.alpha.1-proteinase inhibitor human,abdominal distension,1,7,7.000000
3,.alpha.1-proteinase inhibitor human,abdominal hernia,1,7,7.000000
4,.alpha.1-proteinase inhibitor human,abdominal pain,4,7,4.500000
...,...,...,...,...,...
388368,zyvox,skin disorder,1,4,4.000000
388369,zyvox,skin swelling,1,2,2.000000
388370,zyvox,thrombocytopenia,3,8,7.333333
388371,zyvox,vomiting,1,4,4.000000
388372,zyvox,white blood cell count decreased,1,7,7.000000

In [ ]:
print(pairs.isnull().sum())

drugname              0
reaction              0
complaint_count       0
max_severity_score    0
avg_severity_score    0
dtype: int64

## Calculation of population_score , novelity_score and severity_score

In [29]:
## Population_score

In [16]:
log_vals = np.log1p(demo_df['complaint_count'])

In [ ]:
# demo_df['population_score'] = round((log_vals / np.max(log_vals)) * 10) 
pairs['population_score'] = round((log_vals / np.max(log_vals)) * 10)

In [18]:
# why we use log_vals instead of column , caz the operation should be in same scale.If we keep column then it is original but log_vals is created using log so we used the np.max(log_vals) not np.max(demo_df['complaint_count'])

In [20]:
pairs

,drugname,reaction,complaint_count,max_severity_score,avg_severity_score,population_score
0,.alpha.1-proteinase inhibitor human,abdominal abscess,1,7,7.000000,1.0
1,.alpha.1-proteinase inhibitor human,abdominal discomfort,2,7,4.500000,1.0
2,.alpha.1-proteinase inhibitor human,abdominal distension,1,7,7.000000,1.0
3,.alpha.1-proteinase inhibitor human,abdominal hernia,1,7,7.000000,1.0
4,.alpha.1-proteinase inhibitor human,abdominal pain,4,7,4.500000,2.0
...,...,...,...,...,...,...
388368,zyvox,skin disorder,1,4,4.000000,1.0
388369,zyvox,skin swelling,1,2,2.000000,1.0
388370,zyvox,thrombocytopenia,3,8,7.333333,2.0
388371,zyvox,vomiting,1,4,4.000000,1.0
388372,zyvox,white blood cell count decreased,1,7,7.000000,1.0

In [28]:
## Novelity_score

In [21]:
import requests
import time

# ── STEP 1: Get unique drugs only ──────────────────────────────
unique_drugs = pairs['drugname'].unique().tolist()
print(f"Total unique drugs: {len(unique_drugs)}")

# ── STEP 2: Build cache by looping unique drugs only ───────────
label_cache = {}

for i, drug_name in enumerate(unique_drugs):

    # Progress print every 50 drugs
    if i % 50 == 0:
        print(f"  {i} / {len(unique_drugs)} drugs done...")

    # Skip if already cached (safety check)
    if drug_name in label_cache:
        continue

    url = f"https://api.fda.gov/drug/label.json?search=openfda.generic_name:{drug_name}&limit=1"

    try:
        response = requests.get(url, timeout=5)
        data = response.json()

        if 'results' in data and len(data['results']) > 0:
            label = data['results'][0]
            text_parts = []

            for field in ['adverse_reactions', 'warnings', 'warnings_and_cautions']:
                if field in label:
                    text_parts.append(label[field][0])

            label_cache[drug_name] = ' '.join(text_parts).lower()

        else:
            # API worked but drug not found
            label_cache[drug_name] = ''

    except:
        # Timeout or network error
        label_cache[drug_name] = None

    # Sleep ONLY here — once per unique drug, never inside apply
    time.sleep(0.25)

print(f"Cache built. {len(label_cache)} drugs processed.")


# ── STEP 3: Scoring function — uses cache only, zero API calls ──
def get_novelty_score(drug_name, reaction):
    label_text = label_cache.get(drug_name, None)

    if label_text is None or label_text == '':
        return 5  # Unknown — neutral score

    if reaction.lower() in label_text:
        return 1  # Already on label — not novel

    return 10     # Not on label — novel and dangerous


# ── STEP 4: Apply on pairs — instant, no API, no sleep ─────────
pairs['novelty_score'] = pairs.apply(
    lambda row: get_novelty_score(row['drugname'], row['reaction']),
    axis=1
)

print("Novelty scoring done!")
print(pairs['novelty_score'].value_counts())
print(pairs[['drugname', 'reaction', 'novelty_score']].head(10))

Total unique drugs: 4697
  0 / 4697 drugs done...
  50 / 4697 drugs done...
  100 / 4697 drugs done...
  150 / 4697 drugs done...
  200 / 4697 drugs done...
  250 / 4697 drugs done...
  300 / 4697 drugs done...
  350 / 4697 drugs done...
  400 / 4697 drugs done...
  450 / 4697 drugs done...
  500 / 4697 drugs done...
  550 / 4697 drugs done...
  600 / 4697 drugs done...
  650 / 4697 drugs done...
  700 / 4697 drugs done...
  750 / 4697 drugs done...
  800 / 4697 drugs done...
  850 / 4697 drugs done...
  900 / 4697 drugs done...
  950 / 4697 drugs done...
  1000 / 4697 drugs done...
  1050 / 4697 drugs done...
  1100 / 4697 drugs done...
  1150 / 4697 drugs done...
  1200 / 4697 drugs done...
  1250 / 4697 drugs done...
  1300 / 4697 drugs done...
  1350 / 4697 drugs done...
  1400 / 4697 drugs done...
  1450 / 4697 drugs done...
  1500 / 4697 drugs done...
  1550 / 4697 drugs done...
  1600 / 4697 drugs done...
  1650 / 4697 drugs done...
  1700 / 4697 drugs done...
  1750 / 4697 drugs done...
  1800 / 4697 drugs done...
  1850 / 4697 drugs done...
  1900 / 4697 drugs done...
  1950 / 4697 drugs done...
  2000 / 4697 drugs done...
  2050 / 4697 drugs done...
  2100 / 4697 drugs done...
  2150 / 4697 drugs done...
  2200 / 4697 drugs done...
  2250 / 4697 drugs done...
  2300 / 4697 drugs done...
  2350 / 4697 drugs done...
  2400 / 4697 drugs done...
  2450 / 4697 drugs done...
  2500 / 4697 drugs done...
  2550 / 4697 drugs done...
  2600 / 4697 drugs done...
  2650 / 4697 drugs done...
  2700 / 4697 drugs done...
  2750 / 4697 drugs done...
  2800 / 4697 drugs done...
  2850 / 4697 drugs done...
  2900 / 4697 drugs done...
  2950 / 4697 drugs done...
  3000 / 4697 drugs done...
  3050 / 4697 drugs done...
  3100 / 4697 drugs done...
  3150 / 4697 drugs done...
  3200 / 4697 drugs done...
  3250 / 4697 drugs done...
  3300 / 4697 drugs done...
  3350 / 4697 drugs done...
  3400 / 4697 drugs done...
  3450 / 4697 drugs done...
  3500 / 4697 drugs done...
  3550 / 4697 drugs done...
  3600 / 4697 drugs done...
  3650 / 4697 drugs done...
  3700 / 4697 drugs done...
  3750 / 4697 drugs done...
  3800 / 4697 drugs done...
  3850 / 4697 drugs done...
  3900 / 4697 drugs done...
  3950 / 4697 drugs done...
  4000 / 4697 drugs done...
  4050 / 4697 drugs done...
  4100 / 4697 drugs done...
  4150 / 4697 drugs done...
  4200 / 4697 drugs done...
  4250 / 4697 drugs done...
  4300 / 4697 drugs done...
  4350 / 4697 drugs done...
  4400 / 4697 drugs done...
  4450 / 4697 drugs done...
  4500 / 4697 drugs done...
  4550 / 4697 drugs done...
  4600 / 4697 drugs done...
  4650 / 4697 drugs done...
Cache built. 4697 drugs processed.
Novelty scoring done!
novelty_score
5     247109
10    126534
1      14730
Name: count, dtype: int64
                              drugname                 reaction  novelty_score
0  .alpha.1-proteinase inhibitor human        abdominal abscess             10
1  .alpha.1-proteinase inhibitor human     abdominal discomfort             10
2  .alpha.1-proteinase inhibitor human     abdominal distension             10
3  .alpha.1-proteinase inhibitor human         abdominal hernia             10
4  .alpha.1-proteinase inhibitor human           abdominal pain             10
5  .alpha.1-proteinase inhibitor human     abdominal pain lower             10
6  .alpha.1-proteinase inhibitor human     abdominal pain upper             10
7  .alpha.1-proteinase inhibitor human      abdominal wall cyst             10
8  .alpha.1-proteinase inhibitor human  abnormal loss of weight             10
9  .alpha.1-proteinase inhibitor human                agitation             10

In [22]:
# print("Novelty scoring done!")
print(pairs['novelty_score'].value_counts())

novelty_score
5     247109
10    126534
1      14730
Name: count, dtype: int64

In [30]:
pairs

,drugname,reaction,complaint_count,max_severity_score,avg_severity_score,population_score,novelty_score
0,.alpha.1-proteinase inhibitor human,abdominal abscess,1,7,7.000000,1.0,10
1,.alpha.1-proteinase inhibitor human,abdominal discomfort,2,7,4.500000,1.0,10
2,.alpha.1-proteinase inhibitor human,abdominal distension,1,7,7.000000,1.0,10
3,.alpha.1-proteinase inhibitor human,abdominal hernia,1,7,7.000000,1.0,10
4,.alpha.1-proteinase inhibitor human,abdominal pain,4,7,4.500000,2.0,10
...,...,...,...,...,...,...,...
388368,zyvox,skin disorder,1,4,4.000000,1.0,5
388369,zyvox,skin swelling,1,2,2.000000,1.0,5
388370,zyvox,thrombocytopenia,3,8,7.333333,2.0,5
388371,zyvox,vomiting,1,4,4.000000,1.0,5
388372,zyvox,white blood cell count decreased,1,7,7.000000,1.0,5

### Novelity score takes 4 hr to calculate , So I saved result into Pairs Dataframe .csv named File

In [116]:
rat = pd.read_csv('Pairs Dataframe.csv')

In [117]:
rat

,drugname,reaction,complaint_count,max_severity_score,avg_severity_score,population_score,novelty_score
0,.alpha.1-proteinase inhibitor human,abdominal abscess,1,7,7.000000,1.0,10
1,.alpha.1-proteinase inhibitor human,abdominal discomfort,2,7,4.500000,1.0,10
2,.alpha.1-proteinase inhibitor human,abdominal distension,1,7,7.000000,1.0,10
3,.alpha.1-proteinase inhibitor human,abdominal hernia,1,7,7.000000,1.0,10
4,.alpha.1-proteinase inhibitor human,abdominal pain,4,7,4.500000,2.0,10
...,...,...,...,...,...,...,...
388368,zyvox,skin disorder,1,4,4.000000,1.0,5
388369,zyvox,skin swelling,1,2,2.000000,1.0,5
388370,zyvox,thrombocytopenia,3,8,7.333333,2.0,5
388371,zyvox,vomiting,1,4,4.000000,1.0,5
388372,zyvox,white blood cell count decreased,1,7,7.000000,1.0,5

In [15]:
a = df.groupby(['drugname' , 'reaction'])['primaryid'].count().reset_index(name = 'A')

In [16]:
a

,drugname,reaction,A
0,.alpha.1-proteinase inhibitor human,abdominal abscess,1
1,.alpha.1-proteinase inhibitor human,abdominal discomfort,2
2,.alpha.1-proteinase inhibitor human,abdominal distension,1
3,.alpha.1-proteinase inhibitor human,abdominal hernia,1
4,.alpha.1-proteinase inhibitor human,abdominal pain,4
...,...,...,...
388368,zyvox,skin disorder,1
388369,zyvox,skin swelling,1
388370,zyvox,thrombocytopenia,3
388371,zyvox,vomiting,1
388372,zyvox,white blood cell count decreased,1

In [17]:
b = df.groupby('drugname')['primaryid'].count().reset_index(name = 'drug_total')

In [18]:
b

                                               drugname  drug_total
0                   .alpha.1-proteinase inhibitor human        1086
1                 .delta.8-tetrahydrocannabinol\herbals           7
2     .delta.9-tetrahydrocannabinol\cannabidiol\herbals          27
3                 .delta.9-tetrahydrocannabinol\herbals           8
4          .delta.9-tetrahydrocannabinolic acid\herbals           3
...                                                 ...         ...
4692                                             zyrtec         374
4693                                     zyrtec allergy          11
4694                                           zyrtec-d          14
4695                                             zytiga         141
4696                                              zyvox          54

[4697 rows x 2 columns]

In [19]:
c = df.groupby('reaction')['primaryid'].count().reset_index(name = 'reaction_total')

In [20]:
c

                                 reaction  reaction_total
0        11-deoxycorticosterone increased               1
1        17-hydroxyprogesterone decreased               1
2        17-hydroxyprogesterone increased               6
3               5-hydroxyindolacetic acid               1
4                       abdominal abscess             110
...                                   ...             ...
12721                  yersinia infection               1
12722  zhu-tokita-takenouchi-kim syndrome               1
12723                zika virus infection               1
12724                     zinc deficiency               9
12725                 zoster sine herpete               1

[12726 rows x 2 columns]

In [21]:
d = df.shape[0]

In [22]:
d

1332765

In [23]:
df_pr = a.merge(b , on = 'drugname')

In [24]:
df_pr

,drugname,reaction,A,drug_total
0,.alpha.1-proteinase inhibitor human,abdominal abscess,1,1086
1,.alpha.1-proteinase inhibitor human,abdominal discomfort,2,1086
2,.alpha.1-proteinase inhibitor human,abdominal distension,1,1086
3,.alpha.1-proteinase inhibitor human,abdominal hernia,1,1086
4,.alpha.1-proteinase inhibitor human,abdominal pain,4,1086
...,...,...,...,...
388368,zyvox,skin disorder,1,54
388369,zyvox,skin swelling,1,54
388370,zyvox,thrombocytopenia,3,54
388371,zyvox,vomiting,1,54
388372,zyvox,white blood cell count decreased,1,54

In [26]:
df_pr = df_pr.merge(c , on  = 'reaction')

In [27]:
df_pr

,drugname,reaction,A,drug_total,reaction_total
0,.alpha.1-proteinase inhibitor human,abdominal abscess,1,1086,110
1,.alpha.1-proteinase inhibitor human,abdominal discomfort,2,1086,3767
2,.alpha.1-proteinase inhibitor human,abdominal distension,1,1086,2320
3,.alpha.1-proteinase inhibitor human,abdominal hernia,1,1086,107
4,.alpha.1-proteinase inhibitor human,abdominal pain,4,1086,5616
...,...,...,...,...,...
388368,zyvox,skin disorder,1,54,747
388369,zyvox,skin swelling,1,54,348
388370,zyvox,thrombocytopenia,3,54,2238
388371,zyvox,vomiting,1,54,9814
388372,zyvox,white blood cell count decreased,1,54,2210

In [30]:
df_pr['B'] = df_pr['drug_total'] - df_pr['A']
df_pr['C'] = df_pr['reaction_total'] - df_pr['A']
df_pr['D'] = d - (df_pr['A'] + df_pr['B'] + df_pr['C'])

In [31]:
df_pr

,drugname,reaction,A,drug_total,reaction_total,B,C,D
0,.alpha.1-proteinase inhibitor human,abdominal abscess,1,1086,110,1085,109,1331570
1,.alpha.1-proteinase inhibitor human,abdominal discomfort,2,1086,3767,1084,3765,1327914
2,.alpha.1-proteinase inhibitor human,abdominal distension,1,1086,2320,1085,2319,1329360
3,.alpha.1-proteinase inhibitor human,abdominal hernia,1,1086,107,1085,106,1331573
4,.alpha.1-proteinase inhibitor human,abdominal pain,4,1086,5616,1082,5612,1326067
...,...,...,...,...,...,...,...,...
388368,zyvox,skin disorder,1,54,747,53,746,1331965
388369,zyvox,skin swelling,1,54,348,53,347,1332364
388370,zyvox,thrombocytopenia,3,54,2238,51,2235,1330476
388371,zyvox,vomiting,1,54,9814,53,9813,1322898
388372,zyvox,white blood cell count decreased,1,54,2210,53,2209,1330502

In [67]:
df_pr = df_pr[df_pr['C'] > 0]
df_pr = df_pr[(df_pr['A'] >= 5) & (df_pr['drug_total'] >= 50)]

In [ ]:
# df_pr['PRR'] = (df_pr['A'] / (df_pr['A'] + df_pr['B'])) / (df_pr['C'] / (df_pr['C'] + df_pr['D']))

In [68]:
total_reports = len(df)
df_pr['PRR'] = (df_pr['A'] / df_pr['drug_total']) / (df_pr['reaction_total'] / total_reports)
df_pr['PRR'] = df_pr['PRR'].round(3)

In [72]:
df_pr['PRR'] = df_pr['PRR'].clip(upper=100)

In [74]:
df_pr

,drugname,reaction,A,drug_total,reaction_total,B,C,D,PRR,PRR_log,PRR_norm
21,.alpha.1-proteinase inhibitor human,anxiety,10,1086,4723,1076,4713,1326966,2.598,1.281431,0.090609
25,.alpha.1-proteinase inhibitor human,arthralgia,5,1086,10017,1081,10012,1321667,0.613,0.477710,0.033602
36,.alpha.1-proteinase inhibitor human,back pain,7,1086,4283,1079,4276,1327403,2.006,1.101070,0.077816
48,.alpha.1-proteinase inhibitor human,blood pressure increased,7,1086,3010,1079,3003,1328676,2.854,1.350235,0.095489
56,.alpha.1-proteinase inhibitor human,bronchitis,11,1086,1516,1075,1505,1330174,8.905,2.298821,0.162770
...,...,...,...,...,...,...,...,...,...,...,...
388204,zyrtec,withdrawal syndrome,9,374,545,365,536,1331855,58.847,4.107899,0.291084
388205,zyrtec,wrong technique in product usage process,6,374,4043,368,4037,1328354,5.288,1.839730,0.130208
388268,zytiga,fatigue,5,141,15718,136,15713,1316911,3.007,1.388157,0.098179
388278,zytiga,hospitalisation,6,141,3639,135,3633,1328991,15.585,2.809943,0.199023
388279,zytiga,hot flush,5,141,1239,136,1234,1331390,38.145,3.671100,0.260103

In [75]:
df_pr['PRR'].describe()

count    45492.000000
mean        13.088642
std         24.457952
min          0.028000
25%          1.344000
50%          3.186000
75%         10.126750
max        100.000000
Name: PRR, dtype: float64

In [48]:
rat

,drugname,reaction,complaint_count,max_severity_score,avg_severity_score,population_score,novelty_score
0,.alpha.1-proteinase inhibitor human,abdominal abscess,1,7,7.000000,1.0,10
1,.alpha.1-proteinase inhibitor human,abdominal discomfort,2,7,4.500000,1.0,10
2,.alpha.1-proteinase inhibitor human,abdominal distension,1,7,7.000000,1.0,10
3,.alpha.1-proteinase inhibitor human,abdominal hernia,1,7,7.000000,1.0,10
4,.alpha.1-proteinase inhibitor human,abdominal pain,4,7,4.500000,2.0,10
...,...,...,...,...,...,...,...
388368,zyvox,skin disorder,1,4,4.000000,1.0,5
388369,zyvox,skin swelling,1,2,2.000000,1.0,5
388370,zyvox,thrombocytopenia,3,8,7.333333,2.0,5
388371,zyvox,vomiting,1,4,4.000000,1.0,5
388372,zyvox,white blood cell count decreased,1,7,7.000000,1.0,5

In [79]:
# Drop old PRR column if it exists
rat.drop(columns=['PRR_x' , 'PRR_y' , 'PRR'] , inplace=True)

# Keep only needed columns from df_pr
prr_only = df_pr[['drugname', 'reaction', 'PRR']]

# Merge
rat = rat.merge(prr_only, on=['drugname', 'reaction'], how='left')

# Fill pairs that got filtered out with 0
rat['PRR'] = rat['PRR'].fillna(0)

# Verify
print(rat.columns.tolist())
print(rat.isnull().sum())
print(rat.shape)

['drugname', 'reaction', 'complaint_count', 'max_severity_score', 'avg_severity_score', 'population_score', 'novelty_score', 'PRR']
drugname              0
reaction              0
complaint_count       0
max_severity_score    0
avg_severity_score    0
population_score      0
novelty_score         0
PRR                   0
dtype: int64
(388373, 8)

In [81]:
rat['PRR'].describe()

count    388373.000000
mean          1.533136
std           9.369305
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max         100.000000
Name: PRR, dtype: float64

In [54]:
## Adding into main df

In [52]:
rat['PRR'] = round(df_pr['PRR_norm'] , 3)

In [53]:
rat

,drugname,reaction,complaint_count,max_severity_score,avg_severity_score,population_score,novelty_score,PRR
0,.alpha.1-proteinase inhibitor human,abdominal abscess,1,7,7.000000,1.0,10,0.177
1,.alpha.1-proteinase inhibitor human,abdominal discomfort,2,7,4.500000,1.0,10,0.035
2,.alpha.1-proteinase inhibitor human,abdominal distension,1,7,7.000000,1.0,10,0.030
3,.alpha.1-proteinase inhibitor human,abdominal hernia,1,7,7.000000,1.0,10,0.179
4,.alpha.1-proteinase inhibitor human,abdominal pain,4,7,4.500000,2.0,10,0.044
...,...,...,...,...,...,...,...,...
388368,zyvox,skin disorder,1,4,4.000000,1.0,5,0.250
388369,zyvox,skin swelling,1,2,2.000000,1.0,5,0.303
388370,zyvox,thrombocytopenia,3,8,7.333333,2.0,5,0.250
388371,zyvox,vomiting,1,4,4.000000,1.0,5,0.089
388372,zyvox,white blood cell count decreased,1,7,7.000000,1.0,5,0.177

## Calculating final_score

In [7]:
rat = pd.read_csv('Pairs Dataframe.csv')

In [8]:
rat

,drugname,reaction,complaint_count,max_severity_score,avg_severity_score,population_score,novelty_score
0,.alpha.1-proteinase inhibitor human,abdominal abscess,1,7,7.000000,1.0,10
1,.alpha.1-proteinase inhibitor human,abdominal discomfort,2,7,4.500000,1.0,10
2,.alpha.1-proteinase inhibitor human,abdominal distension,1,7,7.000000,1.0,10
3,.alpha.1-proteinase inhibitor human,abdominal hernia,1,7,7.000000,1.0,10
4,.alpha.1-proteinase inhibitor human,abdominal pain,4,7,4.500000,2.0,10
...,...,...,...,...,...,...,...
388368,zyvox,skin disorder,1,4,4.000000,1.0,5
388369,zyvox,skin swelling,1,2,2.000000,1.0,5
388370,zyvox,thrombocytopenia,3,8,7.333333,2.0,5
388371,zyvox,vomiting,1,4,4.000000,1.0,5
388372,zyvox,white blood cell count decreased,1,7,7.000000,1.0,5

In [9]:
rat['final_score'] = round((0.40 * rat['novelty_score']) + (0.35*rat['avg_severity_score']) + (0.25 * rat['population_score']),2)

In [10]:
rat

,drugname,reaction,complaint_count,max_severity_score,avg_severity_score,population_score,novelty_score,final_score
0,.alpha.1-proteinase inhibitor human,abdominal abscess,1,7,7.000000,1.0,10,6.70
1,.alpha.1-proteinase inhibitor human,abdominal discomfort,2,7,4.500000,1.0,10,5.82
2,.alpha.1-proteinase inhibitor human,abdominal distension,1,7,7.000000,1.0,10,6.70
3,.alpha.1-proteinase inhibitor human,abdominal hernia,1,7,7.000000,1.0,10,6.70
4,.alpha.1-proteinase inhibitor human,abdominal pain,4,7,4.500000,2.0,10,6.08
...,...,...,...,...,...,...,...,...
388368,zyvox,skin disorder,1,4,4.000000,1.0,5,3.65
388369,zyvox,skin swelling,1,2,2.000000,1.0,5,2.95
388370,zyvox,thrombocytopenia,3,8,7.333333,2.0,5,5.07
388371,zyvox,vomiting,1,4,4.000000,1.0,5,3.65
388372,zyvox,white blood cell count decreased,1,7,7.000000,1.0,5,4.70

In [11]:
rat['final_score'].describe()

count    388373.000000
mean          4.355931
std           1.386224
min           1.350000
25%           2.950000
50%           4.600000
75%           4.950000
max           8.750000
Name: final_score, dtype: float64

## polishing database to push MySql workbench

In [12]:
signal_ranked = rat

In [13]:
signal_ranked

,drugname,reaction,complaint_count,max_severity_score,avg_severity_score,population_score,novelty_score,final_score
0,.alpha.1-proteinase inhibitor human,abdominal abscess,1,7,7.000000,1.0,10,6.70
1,.alpha.1-proteinase inhibitor human,abdominal discomfort,2,7,4.500000,1.0,10,5.82
2,.alpha.1-proteinase inhibitor human,abdominal distension,1,7,7.000000,1.0,10,6.70
3,.alpha.1-proteinase inhibitor human,abdominal hernia,1,7,7.000000,1.0,10,6.70
4,.alpha.1-proteinase inhibitor human,abdominal pain,4,7,4.500000,2.0,10,6.08
...,...,...,...,...,...,...,...,...
388368,zyvox,skin disorder,1,4,4.000000,1.0,5,3.65
388369,zyvox,skin swelling,1,2,2.000000,1.0,5,2.95
388370,zyvox,thrombocytopenia,3,8,7.333333,2.0,5,5.07
388371,zyvox,vomiting,1,4,4.000000,1.0,5,3.65
388372,zyvox,white blood cell count decreased,1,7,7.000000,1.0,5,4.70

In [14]:
## add trend_flag and last_updated

In [15]:
from datetime import datetime
signal_ranked['treand_flag'] = 'N/A'
signal_ranked['last_updated'] = datetime.now()

In [16]:
signal_ranked

,drugname,reaction,complaint_count,max_severity_score,avg_severity_score,population_score,novelty_score,final_score,treand_flag,last_updated
0,.alpha.1-proteinase inhibitor human,abdominal abscess,1,7,7.000000,1.0,10,6.70,N/A,2026-04-13 00:49:15.342585
1,.alpha.1-proteinase inhibitor human,abdominal discomfort,2,7,4.500000,1.0,10,5.82,N/A,2026-04-13 00:49:15.342585
2,.alpha.1-proteinase inhibitor human,abdominal distension,1,7,7.000000,1.0,10,6.70,N/A,2026-04-13 00:49:15.342585
3,.alpha.1-proteinase inhibitor human,abdominal hernia,1,7,7.000000,1.0,10,6.70,N/A,2026-04-13 00:49:15.342585
4,.alpha.1-proteinase inhibitor human,abdominal pain,4,7,4.500000,2.0,10,6.08,N/A,2026-04-13 00:49:15.342585
...,...,...,...,...,...,...,...,...,...,...
388368,zyvox,skin disorder,1,4,4.000000,1.0,5,3.65,N/A,2026-04-13 00:49:15.342585
388369,zyvox,skin swelling,1,2,2.000000,1.0,5,2.95,N/A,2026-04-13 00:49:15.342585
388370,zyvox,thrombocytopenia,3,8,7.333333,2.0,5,5.07,N/A,2026-04-13 00:49:15.342585
388371,zyvox,vomiting,1,4,4.000000,1.0,5,3.65,N/A,2026-04-13 00:49:15.342585
388372,zyvox,white blood cell count decreased,1,7,7.000000,1.0,5,4.70,N/A,2026-04-13 00:49:15.342585

In [17]:
# while using the reset_index(drop = True) you cann't use inplcae = True
# signal_ranked.sort_values('final_score',ascending=False , inplace=True).reset_index(drop=True)

In [18]:
signal_ranked = signal_ranked.sort_values('final_score',ascending=False ).reset_index(drop=True)

In [19]:
## check diffenrce with above diffence is how index is changed in both 
## while doing sort_values always do reset_index(drop = True)

In [20]:
signal_ranked.sort_values('final_score',ascending=False)

,drugname,reaction,complaint_count,max_severity_score,avg_severity_score,population_score,novelty_score,final_score,treand_flag,last_updated
0,capivasertib,death,48,10,10.000000,5.0,10,8.75,N/A,2026-04-13 00:49:15.342585
1,dextromethorphan hydrobromide\quinidine sulfate,death,62,10,10.000000,5.0,10,8.75,N/A,2026-04-13 00:49:15.342585
2,sodium zirconium cyclosilicate,death,53,10,9.547170,5.0,10,8.59,N/A,2026-04-13 00:49:15.342585
3,benralizumab,death,48,10,9.500000,5.0,10,8.57,N/A,2026-04-13 00:49:15.342585
4,acalabrutinib,death,27,10,9.592593,4.0,10,8.36,N/A,2026-04-13 00:49:15.342585
...,...,...,...,...,...,...,...,...,...,...
388368,ioversol,throat irritation,1,2,2.000000,1.0,1,1.35,N/A,2026-04-13 00:49:15.342585
388369,xolair pfs,vertigo,1,2,2.000000,1.0,1,1.35,N/A,2026-04-13 00:49:15.342585
388370,ipilimumab,granuloma,2,2,2.000000,1.0,1,1.35,N/A,2026-04-13 00:49:15.342585
388371,ipilimumab,immune-mediated nephritis,1,2,2.000000,1.0,1,1.35,N/A,2026-04-13 00:49:15.342585
388372,abacavir,abdominal pain,1,2,2.000000,1.0,1,1.35,N/A,2026-04-13 00:49:15.342585

In [21]:
signal_ranked

,drugname,reaction,complaint_count,max_severity_score,avg_severity_score,population_score,novelty_score,final_score,treand_flag,last_updated
0,capivasertib,death,48,10,10.000000,5.0,10,8.75,N/A,2026-04-13 00:49:15.342585
1,dextromethorphan hydrobromide\quinidine sulfate,death,62,10,10.000000,5.0,10,8.75,N/A,2026-04-13 00:49:15.342585
2,sodium zirconium cyclosilicate,death,53,10,9.547170,5.0,10,8.59,N/A,2026-04-13 00:49:15.342585
3,benralizumab,death,48,10,9.500000,5.0,10,8.57,N/A,2026-04-13 00:49:15.342585
4,acalabrutinib,death,27,10,9.592593,4.0,10,8.36,N/A,2026-04-13 00:49:15.342585
...,...,...,...,...,...,...,...,...,...,...
388368,ioversol,throat irritation,1,2,2.000000,1.0,1,1.35,N/A,2026-04-13 00:49:15.342585
388369,xolair pfs,vertigo,1,2,2.000000,1.0,1,1.35,N/A,2026-04-13 00:49:15.342585
388370,ipilimumab,granuloma,2,2,2.000000,1.0,1,1.35,N/A,2026-04-13 00:49:15.342585
388371,ipilimumab,immune-mediated nephritis,1,2,2.000000,1.0,1,1.35,N/A,2026-04-13 00:49:15.342585
388372,abacavir,abdominal pain,1,2,2.000000,1.0,1,1.35,N/A,2026-04-13 00:49:15.342585

In [22]:
# renaming avg_severity_score to severity_score

In [23]:
signal_ranked.rename(columns={'avg_severity_score' : 'severity_score'},inplace=True)

In [24]:
# keep only useful columns

In [25]:
signal_ranked.drop(columns='max_severity_score',inplace=True)

In [26]:
signal_ranked

,drugname,reaction,complaint_count,severity_score,population_score,novelty_score,final_score,treand_flag,last_updated
0,capivasertib,death,48,10.000000,5.0,10,8.75,N/A,2026-04-13 00:49:15.342585
1,dextromethorphan hydrobromide\quinidine sulfate,death,62,10.000000,5.0,10,8.75,N/A,2026-04-13 00:49:15.342585
2,sodium zirconium cyclosilicate,death,53,9.547170,5.0,10,8.59,N/A,2026-04-13 00:49:15.342585
3,benralizumab,death,48,9.500000,5.0,10,8.57,N/A,2026-04-13 00:49:15.342585
4,acalabrutinib,death,27,9.592593,4.0,10,8.36,N/A,2026-04-13 00:49:15.342585
...,...,...,...,...,...,...,...,...,...
388368,ioversol,throat irritation,1,2.000000,1.0,1,1.35,N/A,2026-04-13 00:49:15.342585
388369,xolair pfs,vertigo,1,2.000000,1.0,1,1.35,N/A,2026-04-13 00:49:15.342585
388370,ipilimumab,granuloma,2,2.000000,1.0,1,1.35,N/A,2026-04-13 00:49:15.342585
388371,ipilimumab,immune-mediated nephritis,1,2.000000,1.0,1,1.35,N/A,2026-04-13 00:49:15.342585
388372,abacavir,abdominal pain,1,2.000000,1.0,1,1.35,N/A,2026-04-13 00:49:15.342585

In [27]:
## rounding severoty score to 2 places

In [28]:
signal_ranked['severity_score'] = round(signal_ranked['severity_score'] , 2)

In [29]:
signal_ranked

,drugname,reaction,complaint_count,severity_score,population_score,novelty_score,final_score,treand_flag,last_updated
0,capivasertib,death,48,10.00,5.0,10,8.75,N/A,2026-04-13 00:49:15.342585
1,dextromethorphan hydrobromide\quinidine sulfate,death,62,10.00,5.0,10,8.75,N/A,2026-04-13 00:49:15.342585
2,sodium zirconium cyclosilicate,death,53,9.55,5.0,10,8.59,N/A,2026-04-13 00:49:15.342585
3,benralizumab,death,48,9.50,5.0,10,8.57,N/A,2026-04-13 00:49:15.342585
4,acalabrutinib,death,27,9.59,4.0,10,8.36,N/A,2026-04-13 00:49:15.342585
...,...,...,...,...,...,...,...,...,...
388368,ioversol,throat irritation,1,2.00,1.0,1,1.35,N/A,2026-04-13 00:49:15.342585
388369,xolair pfs,vertigo,1,2.00,1.0,1,1.35,N/A,2026-04-13 00:49:15.342585
388370,ipilimumab,granuloma,2,2.00,1.0,1,1.35,N/A,2026-04-13 00:49:15.342585
388371,ipilimumab,immune-mediated nephritis,1,2.00,1.0,1,1.35,N/A,2026-04-13 00:49:15.342585
388372,abacavir,abdominal pain,1,2.00,1.0,1,1.35,N/A,2026-04-13 00:49:15.342585

In [30]:
signal_ranked.isnull().sum()

drugname            0
reaction            0
complaint_count     0
severity_score      0
population_score    0
novelty_score       0
final_score         0
treand_flag         0
last_updated        0
dtype: int64

## pushing data to database

In [31]:
engine = create_engine('mysql+pymysql://root:1771@localhost/pharma_safety')
print("Connected Succesfully !!!")

Connected Succesfully !!!

In [35]:
signal_ranked.to_csv('Signal Rannked.csv')

In [33]:
signal_ranked.to_sql(
    name = 'signals_ranked',
    con=engine,
    if_exists='replace',
    index=False,
    chunksize=1000
)

388373